---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - certsync.secret.sync.example.com
  resources:
  - tlssecretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certsync.secret.sync.example.com
  resources:
  - tlssecretsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - certsync.secret.sync.example.com
  resources:
  - tlssecretsyncs/status
  verbs:
  - get
  - patch
  - update
