apiVersion: certsync.secret.sync.example.com/v1alpha1
kind: TLSSecretSync
metadata:
  labels:
    app.kubernetes.io/name: secret-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: tlssecretsync-sample
spec:
  # TODO(user): Add fields here
